version: "3.8"

services:
  sdxl:
    run:
      context: .
      dockerfile: Dockerfile
      args:
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    environment:
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    volumes:
      - ./data:/outputs
      - ./data:/inputs
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: intel
              count: all
              capabilities: [xpu]
            - driver: nvidia
              count: all
              capabilities: [gpu]
