version: "3.8"

x-common: &common-config
  build:
    context: .
    dockerfile: Dockerfile
    args:
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
  entrypoint: /app/inference.py

  volumes:
    - ./data:/outputs
    - ./data:/inputs
    - .:/app
  deploy:
    resources:
      reservations:
        devices:
          - driver: intel
            count: all
            capabilities: [xpu]
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  isdxl:
    <<: *common-config

  isdxl-cpu:
    <<: *common-config
    environment:
      DEVICE: cpu
      PROMPT: "cat in a bag"
