version: "3.8"

x-common: &common-config
  build:
    context: .
    dockerfile: Dockerfile
    args:
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
  entrypoint: /app/inference.py

  volumes:
    - ./data:/outputs
    - ./data:/inputs
    - .:/app

  privileged: true

  # deploy:
  #   resources:
  #     reservations:
  #       devices:
  #         - driver: nvidia
  #           count: all
  #           capabilities: [gpu]

services:
  isdxl:
    <<: *common-config
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: intel
    #           count: all
    #           capabilities: [xpu]

  isdxl-cpu:
    <<: *common-config
    environment:
      DEVICE: cpu
      PROMPT: "cat in a bag"
    privileged: false
